Repository ltd-profit/omega-package, pull requests merged in 2020-06, with the labels that each got.

#130 Добавил утилиты для LayerMask
  Assets/Source/Package/Utilities.cs
  Assets/Source/UtilitiesAggregator/LayerUtilities.cs
  Assets/Source/UtilitiesAggregator/LayerUtilities.cs.meta
  Assets/Tests/Runtime/Utilities.meta
  Assets/Tests/Runtime/Utilities/LayerUtilitiesTests.cs
  Assets/Tests/Runtime/Utilities/LayerUtilitiesTests.cs.meta
Labels: omega.tools utility, unit-tests

#137 Переработано - перемещен ArrayUtilities.cs
  Assets/Source/UtilitiesAggregator/ArrayUtilities.cs
Labels: rework

#139 Добавлено - перегрузка WaitResult с тайм-аутом
  Assets/Source/Routines/RoutineWithResult.cs
Labels: feature

#141 Добавлено - расширения для EventTriggers
  Assets/Source/CommonExtensions/ListExtensions.cs
  Assets/Source/CommonExtensions/ListExtensions.cs.meta
  Assets/Source/CommonExtensions/SelectableExtensions.cs
  Assets/Source/CommonExtensions/SelectableExtensions.cs.meta
Labels: feature

#140 Добавлено - методы расширения для UnityWebReqest
  Assets/Source/CommonExtensions/UnityWebRequestExtensions.cs
  Assets/Source/CommonExtensions/UnityWebRequestExtensions.cs.meta
Labels: feature

#143 Добавлен SequenceRoutine
  Assets/Source/Routines/Base/SequenceRoutine.cs
  Assets/Source/Routines/Base/SequenceRoutine.cs.meta
  Assets/Source/Routines/RoutineStatic.cs
  Assets/Tests/Runtime/Routines/SequenceRoutineTests.cs
  Assets/Tests/Runtime/Routines/SequenceRoutineTests.cs.meta
  Assets/Tests/Runtime/TimeMeter.cs
Labels: feature

#153 Исправлен прогресс WebRequestRoutine
  Assets/Source/Routines/Web/WebRequestRoutine.cs
  Assets/Source/Routines/Web/WebRequestRoutineWithResult.cs
Labels: bug, minor

#144 Добавлены расширения для рефлексии
  Assets/Source/CommonExtensions/ReflectionExtensions.cs
  Assets/Source/CommonExtensions/ReflectionExtensions.cs.meta
  Assets/Tests/Editor/ReflectionExtensionsTests.cs
  Assets/Tests/Editor/ReflectionExtensionsTests.cs.meta
Labels: feature, minor, omega.tools extensions

#138 Расширен функционал ArrayUtilities
  Assets/Source/UtilitiesAggregator/ArrayUtilities.cs
  Assets/Tests/Editor/ArrayUtilitiesTests.cs
Labels: feature

#159 Исправлены тесты
  Assets/Source/UtilitiesAggregator/ArrayUtilities.cs
  Assets/Tests/Runtime/Routines/RoutineTests.cs
Labels: bug, unit-tests
