Repository ltd-profit/omega-package, pull requests merged in 2020-07, with the labels that each got.

#170 Обновление версии Unity до 2019.4
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/UnityConnectSettings.asset
  ProjectSettings/XRSettings.asset
Labels: major, rework

#157 Исправлено получение прогресса DelayRoutine до первого RoutineUpdate
  Assets/Source/Routines/Base/DelayRoutine.cs
  Assets/Tests/Runtime/Routines/Base/DelayRoutineTests.cs
Labels: bug, omega.routines

#171 Исправлена проблема с отменной рутины вложенными рутинами
  Assets/Source/Routines/Routine.cs
  Assets/Tests/Runtime/Routines/RoutineTests.cs
Labels: bug, minor, omega.routines

#163 Добавлено расширение MissingComponent(Type componentType)
  Assets/Source/CommonExtensions/GameObjectExtensions.cs
Labels: feature, omega.tools extensions

#165 Форматирование StackTrace
  Assets/Source/ExceptionHelper.cs
  Assets/Source/Package/StackTraceUtility.cs
  Assets/Source/Package/StackTraceUtility.cs.meta
  Assets/Source/Routines/RoutineExtension.cs
  Assets/Tests/Runtime/Routines/HighLoad/ObjectRoutineTest.cs
Labels: feature

#173 Удален TryGetComponent
  Assets/Source/CommonExtensions/GameObjectExtensions.cs
  Assets/Source/UtilitiesAggregator/GameObjectUtilities.cs
Labels: api change, major

#166 Добавлено имя рутины
  Assets/Source/Routines/Routine.cs
  Assets/Source/Routines/RoutineExtension.cs
  Assets/Tests/Runtime/Routines/RoutineTests.cs
Labels: feature, omega.routines

#179 Добавлены расширения TryGetComponentInChildren(-Parent) для GameObject и Tranform
  Assets/Source/CommonExtensions/GameObjectExtensions.cs
  Assets/Source/CommonExtensions/TransformExtensions.cs
Labels: feature, minor, omega.tools extensions

#187 Добавлен Catch и переработано исполнение рутин
  Assets/Source/ExceptionHelper.cs
  Assets/Source/Package/StackTraceUtility.cs
  Assets/Source/Routines/Continuations.meta
  Assets/Source/Routines/Continuations/IRoutineContinuation.cs
  Assets/Source/Routines/Continuations/IRoutineContinuation.cs.meta
  Assets/Source/Routines/Continuations/RoutineContinuation.cs
  Assets/Source/Routines/Continuations/RoutineContinuation.cs.meta
  Assets/Source/Routines/Routine.cs
  Assets/Source/Routines/RoutineExecution.cs
  Assets/Source/Routines/RoutineExecution.cs.meta
  Assets/Source/Routines/RoutineExtension.cs
  Assets/Source/Routines/RoutineUtilities.cs
  Assets/Tests/Runtime/Routines/Base/ByEnumeratorTests.cs
  Assets/Tests/Runtime/Routines/Base/DelayRoutineTests.cs
  Assets/Tests/Runtime/Routines/Continuation.meta
  Assets/Tests/Runtime/Routines/Continuation/CatchTests.cs
  Assets/Tests/Runtime/Routines/Continuation/CatchTests.cs.meta
  Assets/Tests/Runtime/Routines/RoutineProgressTests.cs
  Assets/Tests/Runtime/Routines/RoutineTests.cs
Labels: major

#180 Исправлен StackTrace Formatter
  Assets/Source/Package/StackTraceUtility.cs
Labels: bug

#136 Переработано - изменения названий, удалены методы
  Assets/Source/CommonExtensions/GameObjectExtensions.cs
  Assets/Source/CommonExtensions/TransformExtensions.cs
  Assets/Source/Package/StackTraceUtility.cs.meta
  Assets/Source/Routines/Base/FromResultRoutine.cs
  Assets/Source/Routines/Base/FromResultRoutine.cs.meta
  Assets/Source/Routines/Base/RoutineWithResult.cs
  Assets/Source/Routines/Base/RoutineWithResult.cs.meta
  Assets/Source/Routines/Continuations.meta
  Assets/Source/Routines/RoutineExecution.cs.meta
  Assets/Source/Routines/RoutineStatic.cs
  Assets/Source/UtilitiesAggregator/RectTransformUtilities.cs
  Assets/Source/UtilitiesAggregator/TransformUtilities.cs
  Assets/Tests/Editor/RectTransformUtilitiesTests.cs
  Assets/Tests/Editor/TransformUtilityTests.cs
  Assets/Tests/Runtime/Routines/Base/RoutineWithResultTests.cs
  Assets/Tests/Runtime/Routines/Base/RoutineWithResultTests.cs.meta
  Assets/Tests/Runtime/Routines/CompletedRoutineTests.cs
  Assets/Tests/Runtime/Routines/Continuation.meta
  Assets/Tests/Runtime/Routines/RoutineTests.cs
Labels: rework

#174 Добавлен выбор отображения StackTrace в Logger
  Assets/Source/Logger.cs
Labels: feature, minor

#186 Переработано - WebRequestRoutine.GetProgress()
  Assets/Source/Routines/Web/WebRequestRoutine.cs
  Assets/Source/Routines/Web/WebRequestRoutineWithResult.cs
Labels: rework

#162 Отмена рутин
  Assets/Source/Routines/Base/ConvertResultRoutine.cs
  Assets/Source/Routines/Web/WebRequestRoutine.cs
  Assets/Source/Routines/Web/WebRequestRoutineWithResult.cs
Labels: bug, major, omega.routines
